# Spring Application
spring.application.name=backend

# Datasource
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Spring Profile
spring.profiles.active=${SPRING_PROFILE}
