# Datasource
spring.datasource.url=${DEV_DB_URL}
spring.datasource.username=${DEV_DB_USER}
spring.datasource.password=${DEV_DB_PW}

# spring.jpa.hibernate.ddl-auto=create-drop

# Load initial data
# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true
